spring:
  datasource:
    username: root
    password: 123456.a
    url: jdbc:mysql://localhost:3306/zua?serverTimezone=UTC&useUnicode=true&charsetEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

#MyBatisPlus配置
mybatis-plus:
  configuration:
    #MyBatisPlus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8087
  servlet:
    context-path: '/book'
